# Generated by Django 3.1.2 on 2021-01-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_account_deleted'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value', models.CharField(max_length=256)),
                ('current_value', models.CharField(blank=True, max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=10)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('appuser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.appuser')),
            ],
        ),
    ]
