# Generated by Django 3.1.2 on 2021-01-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_deleted'),
        ('users', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='appuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser'),
        ),
    ]
