# Generated by Django 3.1.2 on 2020-12-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='appuser',
        ),
        migrations.AddField(
            model_name='account',
            name='appusers',
            field=models.ManyToManyField(to='users.AppUser'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_owner',
            field=models.BooleanField(default=True),
        ),
    ]
